# Day 1 (Wed, Aug 13)

::: {.callout-note}
## Logistics
All times are Eastern Daylight Time (EDT).

Location: Dewey Room, West Pattee, unless otherwise indicated.
:::

## Morning {- #day_1_am}

### 08:30 am • Breakfast {{< fa mug-hot >}} {{< fa bread-slice >}} {-}

### 09:00 am • Welcome {-}

[Rick Gilmore](directors.qmd#rick-gilmore) and [Alaina Pearce](directors.qmd#alaina-pearce)

[HTML slides](https://penn-state-open-science.github.io/bootcamp-2025-welcome-day-1-welcome/)

### 09:30 am • Open @ Penn State {- #day_1_plenary_1}

- [ScholarSphere](https://scholarsphere.psu.edu), [Alaina Pearce](directors.qmd#alaina-pearce)
- Open Science and the HBCD and ABCD Cohorts, [Koraly Perez-Edgar](presenters.qmd#koraly-pérez-edgar)
- Open scholarship and high performance computing, [Wayne Figurelle](presenters.qmd#wayne-figurelle)
- The [Enhancing Neuro Imaging Genetics Through Meta Analysis (ENIGMA) consortium](https://enigma.ini.usc.edu), [Frank Hillary](program-committee.qmd#frank-hillary)

### 10:15 am • Break {{< fa mug-hot >}} {-}

### 10:45 am • Keynote {- #day_1_plenary_2}

#### Harnessing AI for scientific integrity

[Sarah Rajtmajer](program-committee.qmd#sarah-rajtmajer), Penn State College of IST

::: {.callout-note}
## Location

Foster Auditorium (102 Paterno Library)
:::

### 11:45 am • Lunch {{< fa bottle-water >}} {{< fa bread-slice >}} {-}

## Afternoon {- #day_1_pm}

### 12:00 pm • Movie time

Screening of "[Paywall: The Business of Scholarship](https://en.wikipedia.org/wiki/Paywall:_The_Business_of_Scholarship)" and discussion

### 01:30 pm • Break {{< fa mug-hot >}} {-}

### 01:45 pm • Workshop session 1 {- #day_1_pm_session_1}

| Topic | Presenter | Location | Materials |
|--------------|----------|-------|------|
| Introduction to Jupyter notebooks | | W211A | |
| [Getting credit for sharing your data: Good enough data management practices](sessions.qmd#getting-credit-for-sharing-your-data-part-i-good-enough-data-practices) | [Pearce](directors.qmd#alaina-pearce) | Dewey Room | |

### 02:45 pm • Break {{< fa mug-hot >}} {-}

### 03:00 pm • Workshop session 2 {- #day_1_pm_session_2}

| Topic | Presenter | Location | Materials |
|--------------|----------|-------|------|
| [Quarto (Part I): A tool for open scholarship]((sessions.qmd#quarto-part-i-a-tool-for-open-scholarship)) | [ Gilmore](directors.qmd#directors.qmd#rick-gilmore) | 221A | [slides](https://penn-state-open-science.github.io/bootcamp-2025-quarto-I) ~ [template repo](https://penn-state-open-science.github.io/bootcamp-2025-quarto-I-template) |
| [Questionable research practices](sessions.qmd#questionable-research-practices) |  [Lazar](program-committee.qmd#nicole-lazar) & [Valcin](program-committee.qmd#jennifer-valcin) | Dewey Room |  |

### 04:00 pm • Day 1 wrap-up

### 04:15 pm • End of Day 1 {-}
