---
title: "Day 2 (Thu, Aug 14)"
format: html
---

## Morning {- #day_2_am}

### 08:30 am • Coffee {-}

### 09:00 am • Welcome to Day 2 {-}

### 09:05 am • Open @ Penn State

- [Penn State Data Commons](https://www.datacommons.psu.edu), [Maurie Kelly](presenters.qmd#maurie-kelly)
- [Center for Social Data Analytics (SoDA)](https://soda.la.psu.edu), [Bruce Desmarais](people.qmd#bruce-desmarais)

### 09:30 am • Panel Discussion {- #day_2_plenary_1}

Panel discussion on ethical considerations for open scholarship 

- [Kimberly Petrosky](presenters.qmd#kimberly-petrosky), Penn State Office of Research Protections
- [Nicole Lazar](people.qmd#nicole-lazar), Department of Statistics (Moderator)

<!-- | [Data management: Policies](#howto_data_management_policies) | 102 Marriott Fdn Bldg | [Slides](pdf/2023_OpenScienceBootcamp-DataManagement.pdf) | -->
<!-- | [Responsible & robust research](#howto_responsible_research) | 115 Keller Bldg | [PDF Slides](pdf/Responsible and Robust Research_Open Science Bootcamp.pdf) | -->

### 10:30 am • Break (15 min) {-}

### 10:45 am • Keynote • Foster Auditorium^[102 Paterno Library] {- #day_2_plenary_2}

[Lynda Kellam](presenters.qmd#lynda-kellam), [Data Rescue Project](https://www.datarescueproject.org)

<!-- | Topic | Location | Materials | -->
<!-- |--------------|----------|-------| -->
<!-- | | | | -->

<!-- | [Reproducible workflows with R Markdown & Quarto](#howto_rmarkdown) | 102 Marriott Fdn Bldg |  [HTML Slides](https://penn-state-open-science.github.io/bootcamp-2023-rmarkdown-quarto/) | -->
<!-- | [Replication studies](#howto_replication) | 115 Keller Bldg | [PDF Slides](pdf/OpenScienceBootcamp2023_McManus.pdf) | -->
<!-- | [Preregistration](#howto_preregistration) | Library Marriott Fdn Bldg | [PDF Slides](pdf/PennState_Open_Sci_Boot_Pre_Reg_8_8_23.pdf) | -->

### 11:45 am • Lunch break (90 min) {-}

## Afternoon {- #day_2_pm}

### 01:15 pm • Workshop session 3 {- #day_2_pm_session_3}

| Topic | Location | Materials |
|--------------|----------|-------|
| Getting credit (Part II): Sharing your data ([Pearce](people.qmd#alaina-pearce)) | | |
| Quarto (Part III): Reproducible research reports ([West](people.qmd#john-west)) | | | 

<!-- | [Data management: Practicalities](#howto_data_management_practical) | 102 Marriott Fdn Bldg | [PDF slides](pdf/2023_OpenScienceBootcamp-DataManagement.pdf) | -->
<!-- | [Open science for early career researchers](#howto_early_career) | 115 Keller Bldg | [PDF Slides](pdf/open_sci_for_early_research_careers_2023.pdf) | -->

### 02:15 pm • Break (30 min) {-}

### 02:45 pm • Workshop session 4 {- #day_2_pm_session_4}

| Topic | Location | Materials |
|--------------|----------|-------|
| Getting credit (Part III): Data papers ([Pearce](people.qmd#alaina-pearce)) | | |
| LLMs with Jupyter notebooks ([Li](people.qmd#valerie-li)) | | |

### 03:45 pm • Break (15 min) {-}    

### 04:00 pm • Recap Day 2 {- #day_2_pm_recap}

### 04:15 pm • End of Day 2 {-}

### 04:30 pm • Open scholarship happy hour {- #day_2_happy_hour}
