---
title: "Day 3 (Fri, Aug 15)"
format: html
---

::: {.callout-note}
### Logistics
The Bootcamp ends at noon.
:::

### 08:30 am • Breakfast {{< fa mug-hot >}} {{< fa bread-slice >}} {-}

### 09:00 am • Welcome to Day 3 {-}

[Rick Gilmore](directors.qmd#rick-gilmore) and [Alaina Pearce](directors.qmd#alaina-pearce)

### 09:05 am • Open @ Penn State

- *Inside the [National Synthesis Center for Emergence in the Molecular and Cellular Sciences (NCEMS)](https://ncems.psu.edu)*, [Nicole Lazar](program-committee.qmd#nicole-lazar)
- *Video as data and documentation: [Databrary.org](https://databrary.org) and the [Play & Learning Across a Year (PLAY) project](https://play-project.org)*, [Rick Gilmore](directors.qmd#rick-gilmore)
<!-- - ICDS [Wayne Figurelli]() -->

### 09:30 am • Plenary {-}

#### Open access & licensing

[Danielle Steinhart](presenters.qmd#danielle-steinhart), University Libraries

### 10:30 am • Break {{< fa mug-hot >}} {-}

### 10:45 am • Workshop session 5 {- #day_3_am_session_5}

| Topic | Presenter | Location | Materials |
|--------------|----------|-------|------|
| [*Where to start? Early career panel*](sessions.qmd#where-to-start-open-science-for-early-career-researchers) | [Carlos Almeida](program-committee.qmd#carlos-freitas-almeida), [Kyle Hallisky](presenters.qmd#kyle-hallisky), & [Olivia Beck](presenters.qmd#olivia-beck) | Dewey Room |  |
| [*Harnessing Advanced Cyberinfrastructure for Research: An Introduction to Roar and ICDS Resources*](sessions.qmd#open-access-high-performance-computing) | [Carrie Brown](program-committee.qmd#carrie-brown) | W211A |  |

### 11:45 am • Community Dialogue {-}

Plenary session and group discussion about open scholarship initiatives in 2025-26.

### 12:15 pm • End of workshop  {-}

Lunch on your own.
