---
title: "Schedule"
format: html
---

This section provides an overview about what is happening and when over the 2 1/2 day bootcamp.
See the detailed daily schedules for more information.

## Overview

### Day 1

*Breakfast provided*

*Keynote*: Dr. [Sarah Rajtmajer](people.qmd#sarah-rajtmajer), College of IST, Penn State, Foster Auditorium (102 Pattee)

*Lunch provided*

*Movie screening*: "Paywall: The Business of Scholarship"

*Hands-on workshops*

### Day 2

*Breakfast provided*

*Keynote*: Dr. [Lynda Kellam](presenters.qmd#lynda-kellam), University of Pennsylvania & [Data Rescue Project](https://www.datarescueproject.org), Foster Auditorium (102 Pattee)

*Lunch provided*

*Hands-on workshops*

::: {.callout-important}
### Happy Hour
Please join us for an open scholarship happy hour to follow immediately after the end of the Day 2 program.
:::

### Day 3

*Breakfast provided*

*Plenary session on open access & licensing*

*Hands-on workshops*

::: {.callout-note}
### Logistics
The bootcamp will end at noon, but lunch will *not* be provided.
:::