---
title: "Sessions"
format: html
---

::: {.callout-warning}
## Under construction

This material is in an early draft stage.
:::

## About

This page provides additional information about the workshop sessions and links to presenter notes.

## Day 1 • Wed August 13

### Open @ Penn State

What initiatives and resources are available at Penn State related to open scholarship?

### Workshop Session 1

#### Quarto (Part I): A tool for open scholarship

[Quarto](https://quarto.org) is an open-source scientific and technical publishing system. As the Quarto site suggests, if you have a story to tell with data, you can tell it with Quarto. This workshop will introduce Quarto and show how it can a powerful tool for implementing open scholarship practices. This is the first of three workshops on Quarto.

*Presenter*: [Rick Gilmore](people.qmd#rick-gilmore)

*Prerequisites*: None

*Skill level*: Novice

#### Getting credit for sharing your data (Part I): Good enough data practices

Effective data management is key to research integrity, reproducibility, and making your data useful beyond your own project. Since most researchers have limited time to perfect their workflows, this workshop introduces ‘good enough’ data practices; simple, time-efficient strategies that lay the groundwork for sharing, publishing, and reusing data. You’ll learn how to organize your files using logical directory structures and naming conventions, keep your data tidy and consistent, track changes with version control, and create basic metadata to describe your dataset. By the end of the session, you’ll be equipped with practical tools to make your data easier to manage now and far easier to share later. This is the first of three workshops on *Getting Credit for Sharing Your Data*.

*Presenter*: [Alaina Pearce](people.qmd#alaina-pearce)

*Prerequisites*: None

*Skill level*: Novice

### Workshop Session 2

#### Quarto (Part II): Using the web

Documents rendered from Quarto become even more useful as a tool for open scholarship when one of the outputs is a web site. In this workshop, attendees will learn how to generate web sites and publish them using GitHub pages.

*Presenter*: [Rick Gilmore](people.qmd#rick-gilmore)

*Prerequisites*: Quarto (Part I) or equivalent

*Skill level*: Advanced beginner

#### Intro to Jupyter notebooks

#### Questionable research practices

What are questionable research practices? Why are they questionable? How do we avoid them?

*Presenters*: [Nicole Lazar](people.qmd#nicole-lazar) and [Jennifer Valcin](people.qmd#jennifer-valcin)

*Prerequisites*: None

*Skill level*: Novice

## Day 2 • Thu August 14

### Workshop Session 3

#### Getting credit for sharing your data (Part II): Sharing your data

New funder requirements call for researchers to share their data openly — but simply uploading data files isn't enough. To make data truly reusable, others must be able to find, access, and understand it. This workshop will guide participants through selecting an appropriate data repository and implementing best practices for documenting data with clear, well-structured metadata. We’ll discuss what to consider when choosing a repository, highlighting platforms such as ScholarSphere, Dataverse, the Open Science Framework (OSF), and Databrary. Just as important as where you share your data is how you document it. Metadata provides the essential context—the who, what, when, where, why, and how—that enables others to interpret and build upon your work. We will focus on two essential tools: README files and data dictionaries. By the end of the session, you’ll have the knowledge to identify repository features that meet your needs and the skills to create metadata that supports transparency, reproducibility, and meaningful reuse. This is the second of three workshops on *Getting Credit for Sharing Your Data*.

*Presenter*: [Alaiana Pearce](people.qmd#alaina-pearce)

*Prerequisites*: None

*Skill level*: Novice

#### Quarto (Part III): Reproducible research reports 

*Presenter*: [John West](people.qmd#john-west) 

### Workshop Session 4

#### Getting credit for sharing your data (Part III): Data papers

Sharing data openly is a growing expectation in research but getting formal recognition for the time and effort involved is still a challenge. This workshop introduces one impactful way to gain academic credit for your data: publishing a data paper. Data papers are peer-reviewed journal articles that describe a dataset in detail—how it was collected, its structure, and its potential value for reuse. Data papers can be particularly helpful for researchers as they will: 1) add a peer-reviewed publication to your CV; 2) increase the visibility and usability of your dataset; and 3) provide a way for others to cite your data that will contribute to your citation count. In this hands-on session, we will explore the structure and purpose of data papers, walk through examples, and begin drafting key components based on your own projects. This is the third of three workshops on *Getting Credit for Sharing Your Data*.

*Presenter*: [Alaina Pearce](people.qmd#alaina-pearce)

#### LLMs with Jupyter notebooks 

*Presenter*: [Valerie Li](people.qmd#valerie-li)

## Day 3 • Fri August 15

### Workshop Session 5

#### Where to start? Open science for early career researchers

How can early career researchers start their open science journey (Allen & Mehler, 2019; Kathawalla et al., 2021)?

*Presenters*: ([Carlos Frietas Almeida](people.qmd#carlos-freitas-almeida), [Kyle Hallisky](presenters.qmd#kyle-hallisky))

*Prerequisites*: None

*Skill level*: All

#### Open access high performance computing

*Presenter*: [Carrie Brown](people.qmd#carrie-brown)

*Prerequisites*: None

*Skill level*: All